<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Meal extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($meal) {
            if (is_null($meal->position)) {
                $maxpos = Meal::query()->max('position');
                $meal->position = $maxpos + 1;
            }
        });
    }


    public function products(){
        return $this->belongsToMany(Product::class,'meal_products');
    }
}
